export const GET_TEXT = 'GET_TEXT';
export const TOGGLE = 'TOGGLE';
export const SHOW_OVERLAY = 'SHOW_OVERLAY';
export const SELECTED_INDEX = 'SELECTED_INDEX';
export const SELECTED_COUNTRY_PICKER = 'SELECTED_COUNTRY_PICKER';
export const SELECTED_CATEGORY_PICKER = 'SELECTED_CATEGORY_PICKER';

export const RECORDS_FETCH = 'RECORDS_FETCH';
export const RECORDS_FAILED = 'RECORDS_FAILED';
export const RECORDS_SUCCEEDED = 'RECORDS_SUCCEEDED';
export const RECORDS_REQUEST_IN_PROGRESS = 'RECORDS_REQUEST_IN_PROGRESS';

export const REALM_DATA = 'REALM_DATAS';
export const GET_DATA_FROM_REALM = 'GET_DATAS_FROM_REALM';
export const DELETE_DATA_FROM_REALM = 'DELETE_DATA_FROM_REALM';

export const SHOW_ACTIVITY_INDICATOR = 'SHOW_ACTIVITY_INDICATOR';
export const HIDE_ACTIVITY_INDICATOR = 'HIDE_ACTIVITY_INDICATOR';